defaults: &defaults
  adapter: postgresql
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_development
test:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_test
production:
  <<: *defaults
  database: <%= ENV['DB_NAME'] %>_production
